FROM nginx:1.19.9

ARG LANG=en_US.UTF-8

RUN apt-get autoclean                          &&  \
    apt-get update                             &&  \
    apt-get install -y locales                 &&  \
    localedef -f UTF-8 -i ${LANG%%.UTF-8} $LANG && \
    apt-get install -y                             \
      certbot                                      \
      dnsutils                                     \
      python3-certbot-nginx &&                     \
    mkdir -p /var/www/default
